server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: /
  error:
    path: /error

spring:
  jmx:
    enabled: true
  application:
    name: ${APP_NAME:unnamed}
    admin:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://oasystemmysql:3306/portal?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: portal
    password: sqlpass_of_portal
    # HikariCP配置:
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1

management:
  access:
    iplist:
      172.192.1.100             # 自定义actuator IP访问白名单
  endpoints:                    # 暴露 EndPoint 以供访问，有jmx和web两种方式，exclude 的优先级高于 include
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"
        # include: ["health","info","beans","mappings","logfile","metrics","shutdown","env"]
      base-path: /oasystem/actuator
#      cors: # 配置跨域资源共享
#        allowed-origins: http://localhost/
#        allowed-methods: GET,POST
    enabled-by-default: true    # 修改全局 endpoint 默认设置
  endpoint:
    auditevents:                # 1、显示当前引用程序的审计事件信息，默认开启
      enabled: true
      cache:
        time-to-live: 10s       # 配置端点缓存响应的时间
    beans:                      # 2、显示一个应用中所有 Spring Beans 的完整列表，默认开启
      enabled: true
    conditions:                 # 3、显示配置类和自动配置类的状态及它们被应用和未被应用的原因，默认开启
      enabled: true
    configprops:                # 4、显示一个所有@ConfigurationProperties的集合列表，默认开启
      enabled: true
    env:                        # 5、显示来自Spring的 ConfigurableEnvironment的属性，默认开启
      enabled: true
    flyway:                     # 6、显示数据库迁移路径，如果有的话，默认开启
      enabled: true
    health:                     # 7、显示健康信息，默认开启
      enabled: true
      show-details: always
    info:                       # 8、显示任意的应用信息，默认开启
      enabled: true
    liquibase:                  # 9、展示任何Liquibase数据库迁移路径，如果有的话，默认开启
      enabled: true
    metrics:                    # 10、展示当前应用的metrics信息，默认开启
      enabled: true
    mappings:                   # 11、显示一个所有@RequestMapping路径的集合列表，默认开启
      enabled: true
    scheduledtasks:             # 12、显示应用程序中的计划任务，默认开启
      enabled: true
    sessions:                   # 13、允许从Spring会话支持的会话存储中检索和删除(retrieval and deletion)用户会话。使用Spring Session对反应性Web应用程序的支持时不可用。默认开启。
      enabled: true
    shutdown:                   # 14、允许应用以优雅的方式关闭，默认关闭
      enabled: true
    threaddump:                 # 15、执行一个线程dump
      enabled: true
    # web 应用时可以使用以下端点
    heapdump:                   # 16、返回一个GZip压缩的hprof堆dump文件，默认开启
      enabled: true
    jolokia:                    # 17、通过HTTP暴露JMX beans（当Jolokia在类路径上时，WebFlux不可用），默认开启
      enabled: true
    logfile:                    # 18、返回日志文件内容（如果设置了logging.file或logging.path属性的话），支持使用HTTP Range头接收日志文件内容的部分信息，默认开启
      enabled: true
    prometheus:                 # 19、以可以被Prometheus服务器抓取的格式显示metrics信息，默认开启
      enabled: true

pebble:
  suffix:
  cache: false

logging:
  level:
    org:
      springframework:
        security: DEBUG
    hibernate: DEBUG
  file:
    name: logs/app.log
    clean-history-on-start: true
    max-size: 10MB
